services:
  - type: web
    name: algerian-forest-fire-prediction
    env: python
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT main:app
    plan: free
    region: oregon
    branch: main